Vagrant.configure("2") do |config|

config.vm.define :clienteNAT do |clienteNAT|
clienteNAT.vm.box = "centos/stream8"
clienteNAT.vm.network :private_network, ip: "192.168.50.2"
clienteNAT.vm.hostname = "clienteNAT"
end
config.vm.define :firewallNAT do |firewallNAT|
firewallNAT.vm.box = "centos/stream8"
firewallNAT.vm.network :private_network, ip: "192.168.50.3"
firewallNAT.vm.hostname = "firewallNAT"
end
end